// FOR Fetching Content
export const FETCH_CONTENT_REQUEST = "FETCH_CONTENT_REQUEST"
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS"
export const FETCH_CONTENT_FALIURE = "FETCH_CONTENT_FALIURE"



// FOR Fetching Content
export const FETCH_SINGLE_CONTENT_REQUEST = "FETCH_SINGLE_CONTENT_REQUEST"
export const FETCH_SINGLE_CONTENT_SUCCESS = "FETCH_SINGLE_CONTENT_SUCCESS"
export const FETCH_SINGLE_CONTENT_FALIURE = "FETCH_SINGLE_CONTENT_FALIURE"

// FOR Audio Content
export const AUDIO_REQUEST = "AUDIO_REQUEST"
export const AUDIO_SUCCESS = "AUDIO_SUCCESS"
export const AUDIO_FALIURE = "AUDIO_FALIURE"

// FOR Audio Content
export const EDIT_AUDIO_REQUEST = "EDIT_AUDIO_REQUEST"
export const EDIT_AUDIO_SUCCESS = "EDIT_AUDIO_SUCCESS"
export const EDIT_AUDIO_FALIURE = "EDIT_AUDIO_FALIURE"

// FOR FILE Content
export const FILE_REQUEST = "FILE_REQUEST"
export const FILE_SUCCESS = "FILE_SUCCESS"
export const FILE_FALIURE = "FILE_FALIURE"

// FOR FILE Content
export const EDIT_FILE_REQUEST = "EDIT_FILE_REQUEST"
export const EDIT_FILE_SUCCESS = "EDIT_FILE_SUCCESS"
export const EDIT_FILE_FALIURE = "EDIT_FILE_FALIURE"

// FOR VIDEO Content
export const VIDEO_REQUEST = "VIDEO_REQUEST"
export const VIDEO_SUCCESS = "VIDEO_SUCCESS"
export const VIDEO_FALIURE = "VIDEO_FALIURE"

// FOR VIDEO Content
export const EDIT_VIDEO_REQUEST = "EDIT_VIDEO_REQUEST"
export const EDIT_VIDEO_SUCCESS = "EDIT_VIDEO_SUCCESS"
export const EDIT_VIDEO_FALIURE = "EDIT_VIDEO_FALIURE"

//FOR DELETE CONTENT
export const DELETE_CONTENT_REQUEST = "DELETE_CONTENT_REQUEST"
export const DELETE_CONTENT_SUCCESS = "DELETE_CONTENT_SUCCESS"
export const DELETE_CONTENT_FALIURE = "DELETE_CONTENT_FALIURE"
