// FOR create playlist
export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST"
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS"
export const CREATE_PLAYLIST_FALIURE = "CREATE_PLAYLIST_FALIURE"

// FOR create playlist
export const CREATE_SECTION_REQUEST = "CREATE_SECTION_REQUEST"
export const CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS"
export const CREATE_SECTION_FALIURE = "CREATE_SECTION_FALIURE"

// FOR create playlist
export const CREATE_CONTENT_REQUEST = "CREATE_CONTENT_REQUEST"
export const CREATE_CONTENT_SUCCESS = "CREATE_CONTENT_SUCCESS"
export const CREATE_CONTENT_FALIURE = "CREATE_CONTENT_FALIURE"
