// FOR Fetching Content
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FALIURE = "CHANGE_PASSWORD_FALIURE"


// FOR Fetching Content
export const CHANGE_PROFILE_IMAGE_REQUEST = "CHANGE_PROFILE_IMAGE_REQUEST"
export const CHANGE_PROFILE_IMAGE_SUCCESS = "CHANGE_PROFILE_IMAGE_SUCCESS"
export const CHANGE_PROFILE_IMAGE_FALIURE = "CHANGE_PROFILE_IMAGE_FALIURE"

// FOR Fetching Content
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FALIURE = "UPDATE_PROFILE_FALIURE"
